import { BaseReporter } from "./base-reporter.js";
import { MarkdownReporter } from "./markdown-reporter.js";
import type { Report } from "./types.js";
import { marked } from "marked";
import Handlebars from "handlebars";

export class HTMLReporter extends BaseReporter {
  private markdownReporter: MarkdownReporter;

  constructor() {
    super();
    this.markdownReporter = new MarkdownReporter();
  }

  getFormat(): "markdown" | "html" {
    return "html";
  }

  async generate(report: Report): Promise<string> {
    // Generate markdown first
    const markdown = await this.markdownReporter.generate(report);

    // Convert to HTML
    const contentHtml = await marked(markdown);

    // Apply template
    const template = this.getTemplate();
    const compiled = Handlebars.compile(template);

    return compiled({
      title: "Code Review Report",
      content: contentHtml,
      generatedAt: report.generatedAt.toLocaleString(),
      summary: report.summary,
    });
  }

  private getTemplate(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #f5f5f5;
      padding: 20px;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      padding: 40px;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    }

    h1 {
      color: #2c3e50;
      border-bottom: 3px solid #3498db;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }

    h2 {
      color: #34495e;
      margin-top: 30px;
      margin-bottom: 15px;
      padding-bottom: 8px;
      border-bottom: 2px solid #ecf0f1;
    }

    h3 {
      color: #555;
      margin-top: 20px;
      margin-bottom: 10px;
    }

    h4 {
      color: #666;
      margin-top: 15px;
      margin-bottom: 8px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }

    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }

    th {
      background-color: #3498db;
      color: white;
      font-weight: 600;
    }

    tr:hover {
      background-color: #f5f5f5;
    }

    code {
      background: #f4f4f4;
      padding: 2px 6px;
      border-radius: 3px;
      font-family: 'Courier New', monospace;
      font-size: 0.9em;
      color: #e74c3c;
    }

    pre {
      background: #2c3e50;
      color: #ecf0f1;
      padding: 15px;
      border-radius: 5px;
      overflow-x: auto;
      margin: 15px 0;
    }

    pre code {
      background: transparent;
      color: #ecf0f1;
      padding: 0;
    }

    hr {
      border: none;
      border-top: 1px solid #ecf0f1;
      margin: 20px 0;
    }

    strong {
      color: #2c3e50;
    }

    ul, ol {
      margin-left: 30px;
      margin-bottom: 15px;
    }

    li {
      margin-bottom: 8px;
    }

    .summary-box {
      background: #ecf0f1;
      padding: 20px;
      border-radius: 5px;
      margin: 20px 0;
    }

    .badge {
      display: inline-block;
      padding: 4px 8px;
      border-radius: 3px;
      font-size: 0.85em;
      font-weight: 600;
      margin-right: 5px;
    }

    .badge-critical {
      background: #e74c3c;
      color: white;
    }

    .badge-high {
      background: #e67e22;
      color: white;
    }

    .badge-medium {
      background: #f39c12;
      color: white;
    }

    .badge-low {
      background: #27ae60;
      color: white;
    }

    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ecf0f1;
      text-align: center;
      color: #7f8c8d;
      font-size: 0.9em;
    }

    @media print {
      body {
        background: white;
        padding: 0;
      }

      .container {
        box-shadow: none;
        padding: 20px;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    {{{content}}}
    
    <div class="footer">
      <p>Generated by Code Review Automation</p>
      <p>{{generatedAt}}</p>
    </div>
  </div>
</body>
</html>`;
  }
}
